"use client";

import { Fragment, useEffect, useMemo, useRef, useState } from "react";

type BrandYear={id:string;chainId:string;brand:string;year:number;score:number|null;status:string;paperReady:boolean;documents:number;versions:number;sources:string[];forms:string[];providers:string[];purposes:string[];evidenceQuote:string;hasFullText:boolean;qcStatus?:string;qcReason?:string};
type Version={hash:string;source:string;efdId:string;docId:string;issuanceDate?:string;score:number|null;forms:string[];providers:string[];purposes:string[];riskTransfer:string;evidenceQuote:string;codingNote:string;item10Text:string};
type Detail={id:string;brand:string;year:number;score:number|null;status:string;versions:Version[]};
type Change={id:string;chainId:string;brand:string;fromYear:number;toYear:number;fromScore:number;toScore:number;scoreChange:number;changeType:string;fromForms:string[];toForms:string[];fromProviders:string[];toProviders:string[];fromQuote:string;toQuote:string;fromId:string;toId:string};
type DetailAlias={oldId:string;targetScore:number|null};
type PatchUpdate={id:string;changes:Partial<BrandYear>};
type PatchAdd={id:string;cloneId:string;changes:Partial<BrandYear>};
type MiniPatch={meta:{v:string;n:number;paper:number;unresolved:number;changes:number};remove:string[];updates:PatchUpdate[];adds:PatchAdd[];qc:Record<string,string>;notes:Record<string,string>;aliases:Record<string,DetailAlias>};
type ChangePatch={meta:{version:string;n:number};removeIds:string[];upsertRows:Change[]};
type PatchBundle={brand:MiniPatch;within:ChangePatch};

const PAGE=24;
const pretty=(x:string)=>x.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const joined=(x:string[])=>x?.length?x.map(pretty).join(" · "):"—";
const displayBrand=(chainId:string,brand:string)=>brand.replaceAll("â„¢","™");

const qcLabels:Record<string,string>={
 VERIFIED_STATE_SPECIFIC_RETAINED:"Verified state-specific disclosure difference",
 SAME_SOURCE_PARALLEL_VERSION_RETAINED:"Same-source parallel versions",
 INSUFFICIENT_CHRONOLOGY_METADATA_RETAINED:"Insufficient chronology metadata",
 IDENTITY_YEAR_REVIEW_RETAINED:"Identity / filing-year review",
 CHRONOLOGY_CANDIDATE_SCOPE_NOT_SAFE_RETAINED:"Chronology candidate — scope not safe",
 OFFERING_SCOPE_CLARIFIED_STATE_CONFLICT_RETAINED:"Offering scope clarified; state conflict remains",
};
const qcOrder=Object.keys(qcLabels);
const qcLabel=(r:BrandYear)=>qcLabels[r.qcStatus||""]||"Other retained V1.2 conflict";
const qcCodes:Record<string,string>={S:"VERIFIED_STATE_SPECIFIC_RETAINED",P:"SAME_SOURCE_PARALLEL_VERSION_RETAINED",M:"INSUFFICIENT_CHRONOLOGY_METADATA_RETAINED",I:"IDENTITY_YEAR_REVIEW_RETAINED",C:"CHRONOLOGY_CANDIDATE_SCOPE_NOT_SAFE_RETAINED",O:"OFFERING_SCOPE_CLARIFIED_STATE_CONFLICT_RETAINED",R:"V1_2_CHRONOLOGY_RESOLVED",F:"V1_2_OFFERING_SCOPE_SPLIT"};
const standardReasons:Record<string,string>={
 VERIFIED_STATE_SPECIFIC_RETAINED:"Contemporaneous state-specific FDD versions contain substantively different Item 10 financing disclosures. Chronology does not establish one national controlling score, so the system-year remains NA.",
 SAME_SOURCE_PARALLEL_VERSION_RETAINED:"Multiple Item 10 versions within the same source/date remain substantively different and cannot be safely ordered as superseding versions. The system-year remains NA.",
 INSUFFICIENT_CHRONOLOGY_METADATA_RETAINED:"The available filing metadata are insufficient to establish a safe supersession order among conflicting Item 10 versions. The system-year remains NA.",
 IDENTITY_YEAR_REVIEW_RETAINED:"The remaining conflict is tied to identity or filing-year ambiguity that cannot be safely resolved in the national system-year panel. The observation remains NA.",
 CHRONOLOGY_CANDIDATE_SCOPE_NOT_SAFE_RETAINED:"A possible later-version ordering exists, but offering scope or cover-page evidence is not sufficient to apply the latest-version rule safely. The observation remains NA.",
 OFFERING_SCOPE_CLARIFIED_STATE_CONFLICT_RETAINED:"Offering scope was clarified in V1.2, but substantively different state-specific Item 10 versions still remain within this offering/year. The observation remains NA.",
 V1_2_CHRONOLOGY_RESOLVED:"A later amendment/version unambiguously supersedes the earlier version within the same offering scope, so V1.2 uses the later controlling score.",
 V1_2_OFFERING_SCOPE_SPLIT:"V1.2 separates distinct franchise offerings/programs that should not share one system-year score.",
};
async function loadPatchBundle(url:string):Promise<PatchBundle>{
 const r=await fetch(url); if(!r.ok)throw Error("V1.2 QC patch could not be loaded.");
 const b64=(await r.text()).trim();
 const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
 const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));
 return JSON.parse(await new Response(stream).text()) as PatchBundle;
}

function Badge({score}:{score:number|null}){return <span className={`financing-score-badge score-${score??"na"}`}>{score??"NA"}</span>}
function Pager({page,pages,setPage}:{page:number;pages:number;setPage:(n:number)=>void}){return pages<=1?null:<div className="financing-pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next →</button></div>}

function VersionCard({version,index}:{version:Version;index:number}){
 return <article className="financing-version-card compact"><div className="financing-version-head"><div><span>Item 10 version {index+1}</span><strong>{version.source||"Source not recorded"}{version.issuanceDate?` · ${version.issuanceDate}`:""}</strong><small>{version.efdId?`${version.efdId}${version.docId?` / ${version.docId}`:""}`:version.docId||""}</small></div><Badge score={version.score}/></div><dl className="financing-detail-grid"><div><dt>Provider</dt><dd>{joined(version.providers)}</dd></div><div><dt>Financing form</dt><dd>{joined(version.forms)}</dd></div><div><dt>Purpose</dt><dd>{joined(version.purposes)}</dd></div><div><dt>Risk transfer</dt><dd>{pretty(version.riskTransfer||"not recorded")}</dd></div></dl>{version.evidenceQuote&&<blockquote><span>Score-specific evidence</span>{version.evidenceQuote}</blockquote>}<details className="financing-original-text"><summary>Open full extracted Item 10 text</summary>{version.item10Text?<pre>{version.item10Text}</pre>:<p>Full extracted text is not available in the assembled website data; the evidence quote above is the text used for coding.</p>}</details>{version.codingNote&&<p className="financing-coding-note"><strong>Coding note:</strong> {version.codingNote}</p>}</article>
}

function InlineBrandDetail({row,detail,loading,onClose}:{row:BrandYear;detail:Detail|null;loading:boolean;onClose:()=>void}){
 return <div className="financing-inline-detail"><div className="financing-inline-detail-head"><div><span>{row.score===null?"V1.2 UNRESOLVED ITEM 10 VERSIONS":"BRAND-YEAR EVIDENCE"}</span><h3>{displayBrand(row.chainId,row.brand)} · {row.year}</h3></div><button onClick={onClose}>Close</button></div>{loading&&<div className="financing-loading">Loading source-specific Item 10 versions…</div>}{!loading&&detail&&<>{row.qcStatus&&row.qcStatus!=="UNCHANGED_V1_1"&&<div className="financing-conflict-explanation"><strong>V1.2 QC status: {row.score===null?qcLabel(row):pretty(row.qcStatus)}</strong><p>{row.qcReason||"V1.2 chronology / identity QC updated this observation."}</p>{row.score===null&&<p className="financing-conflict-instruction">Compare the <b>source/state, filing date, score, and score-specific evidence</b> below. The production freeze keeps this row NA because no safe national controlling score was established.</p>}</div>}<div className={`financing-inline-versions${detail.versions.length>1?" compare":""}`}>{detail.versions.map((v,i)=><VersionCard key={`${v.hash}-${i}`} version={v} index={i}/>)}</div></>}</div>
}

export default function EvidenceExplorer({basePath}:{basePath:string}){
 const [mode,setMode]=useState<"brand"|"changes">("brand"),[rows,setRows]=useState<BrandYear[]>([]),[changes,setChanges]=useState<Change[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [query,setQuery]=useState(""),[year,setYear]=useState("all"),[score,setScore]=useState("all"),[status,setStatus]=useState("paper"),[reason,setReason]=useState("all"),[kind,setKind]=useState("all"),[page,setPage]=useState(1);
 const [selected,setSelected]=useState<BrandYear|null>(null),[detail,setDetail]=useState<Detail|null>(null),[selectedChange,setSelectedChange]=useState<Change|null>(null),[compare,setCompare]=useState<{before:Detail;after:Detail}|null>(null),[detailLoading,setDetailLoading]=useState(false);
 const cache=useRef(new Map<number,Record<string,Detail>>()),patchRef=useRef<MiniPatch|null>(null);
 useEffect(()=>{let active=true;Promise.all([
   fetch(`${basePath}/data/item10-financing/brand-year-index.json`).then(r=>{if(!r.ok)throw Error("Brand-year evidence could not be loaded.");return r.json()}),
   fetch(`${basePath}/data/item10-financing/within-firm-changes.json`).then(r=>{if(!r.ok)throw Error("V1.1 within-firm base could not be loaded.");return r.json()}),
   loadPatchBundle(`${basePath}/data/item10-financing/v1.2-patches.b64`),
 ]).then(([base,chgBase,bundle]:[{rows:BrandYear[]},{rows:Change[]},PatchBundle])=>{if(!active)return;const patch=bundle.brand,chgPatch=bundle.within;patchRef.current=patch;const original=new Map(base.rows.map(r=>[r.id,r]));const byId=new Map(base.rows.map(r=>[r.id,{...r}]));for(const u of patch.updates){const row=byId.get(u.id);if(row)byId.set(u.id,{...row,...u.changes})}for(const a of patch.adds){const src=original.get(a.cloneId);if(src)byId.set(a.id,{...src,id:a.id,...a.changes})}for(const id of patch.remove)byId.delete(id);for(const [id,code] of Object.entries(patch.qc)){const row=byId.get(id);if(!row)continue;const qcStatus=qcCodes[code]||code;byId.set(id,{...row,qcStatus,qcReason:patch.notes[id]||standardReasons[qcStatus]||"V1.2 chronology / identity QC reviewed this observation."})}setRows(Array.from(byId.values()));const chgRemove=new Set(chgPatch.removeIds);const chgById=new Map(chgBase.rows.filter(r=>!chgRemove.has(r.id)).map(r=>[r.id,r]));for(const r of chgPatch.upsertRows)chgById.set(r.id,r);setChanges(Array.from(chgById.values()));setLoading(false)}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false}},[basePath]);
 async function yearDetails(y:number){const old=cache.current.get(y);if(old)return old;const r=await fetch(`${basePath}/data/item10-financing/details/${y}.json`);if(!r.ok)throw Error("Original text could not be loaded.");const d=await r.json();cache.current.set(y,d);return d}
 async function resolveDetail(id:string,brand:string,yearValue:number){const d=await yearDetails(yearValue);const direct=d[id];if(direct)return {...direct,brand};const alias=patchRef.current?.aliases[id];if(!alias)return null;const old=d[alias.oldId];if(!old)return null;let versions=old.versions||[];if(alias.targetScore!==null){const filtered=versions.filter((v:Version)=>v.score===alias.targetScore);if(filtered.length)versions=filtered}return {...old,id,brand,year:yearValue,score:alias.targetScore,versions};}
 async function openRow(r:BrandYear){if(selected?.id===r.id){setSelected(null);setDetail(null);return}setSelected(r);setSelectedChange(null);setCompare(null);setDetail(null);setDetailLoading(true);try{setDetail(await resolveDetail(r.id,r.brand,r.year))}catch(e){setError(e instanceof Error?e.message:"Original text could not be loaded.")}finally{setDetailLoading(false)}}
 async function openChange(r:Change){setSelectedChange(r);setSelected(null);setDetail(null);setCompare(null);setDetailLoading(true);try{const[a,b]=await Promise.all([resolveDetail(r.fromId,r.brand,r.fromYear),resolveDetail(r.toId,r.brand,r.toYear)]);if(a&&b)setCompare({before:a,after:b});else throw Error("Comparison text could not be resolved for this V1.2 split/identity row.")}catch(e){setError(e instanceof Error?e.message:"Comparison text could not be loaded.")}finally{setDetailLoading(false)}}
 const years=useMemo<number[]>(()=>Array.from(new Set<number>(rows.map(r=>r.year))).sort((a,b)=>b-a),[rows]),q=query.trim().toLowerCase();
 const reasonCounts=useMemo(()=>{const out:Record<string,number>={};qcOrder.forEach(k=>out[k]=0);rows.filter(r=>!r.paperReady&&r.status==="UNRESOLVED_SCORE_CONFLICT").forEach(r=>out[r.qcStatus||""]=(out[r.qcStatus||""]||0)+1);return out},[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(!q||[displayBrand(r.chainId,r.brand),r.brand,r.chainId,...r.forms,...r.providers,...r.purposes,r.evidenceQuote,r.qcReason||""].join(" ").toLowerCase().includes(q))&&(year==="all"||r.year===+year)&&(score==="all"||(score==="na"?r.score===null:r.score===+score))&&(status==="all"||(status==="paper"?r.paperReady:!r.paperReady&&r.status==="UNRESOLVED_SCORE_CONFLICT"))&&(status!=="unresolved"||reason==="all"||r.qcStatus===reason)),[rows,q,year,score,status,reason]);
 const filteredChanges=useMemo(()=>changes.filter(r=>{const match=kind==="all"||(kind==="0 → support"&&r.fromScore===0&&r.toScore>0)||(kind==="support → 0"&&r.fromScore>0&&r.toScore===0)||(kind==="risk increase"&&r.scoreChange>0)||(kind==="risk decrease"&&r.scoreChange<0)||(kind==="low → material"&&r.fromScore<=2&&r.toScore>=3)||(kind==="material → low"&&r.fromScore>=3&&r.toScore<=2);return match&&(year==="all"||r.toYear===+year)&&(!q||[displayBrand(r.chainId,r.brand),r.brand,r.chainId,...r.fromForms,...r.toForms,r.fromQuote,r.toQuote].join(" ").toLowerCase().includes(q))}),[changes,q,year,kind]);
 const active=mode==="brand"?filtered:filteredChanges,pages=Math.max(1,Math.ceil(active.length/PAGE)),p=Math.min(page,pages),visible=active.slice((p-1)*PAGE,p*PAGE);
 const visibleBrand=visible as BrandYear[],visibleChangeRows=visible as Change[];
 const reset=(fn:()=>void)=>{fn();setPage(1);setSelected(null);setDetail(null);setSelectedChange(null);setCompare(null)};
 return <div className="financing-explorer">
   <div className="financing-explorer-tabs" role="tablist"><button role="tab" aria-selected={mode==="brand"} onClick={()=>reset(()=>setMode("brand"))}>Brand-year evidence <span>{rows.length.toLocaleString()}</span></button><button role="tab" aria-selected={mode==="changes"} onClick={()=>reset(()=>setMode("changes"))}>Within-firm changes <span>{changes.length.toLocaleString()}</span></button></div>
   <div className={`financing-filters${mode==="brand"&&status==="unresolved"?" has-conflict-filter":""}`}><label className="financing-search"><span>Search brand, form, provider or text</span><input value={query} onChange={e=>reset(()=>setQuery(e.target.value))} placeholder="e.g., McDonald's, guarantee, deferred fee"/></label><label><span>Year</span><select value={year} onChange={e=>reset(()=>setYear(e.target.value))}><option value="all">All years</option>{years.map(y=><option key={y}>{y}</option>)}</select></label>{mode==="brand"?<><label><span>Risk score</span><select value={score} onChange={e=>reset(()=>setScore(e.target.value))}><option value="all">All scores</option>{[0,1,2,3,4].map(s=><option key={s} value={s}>Score {s}</option>)}<option value="na">NA / conflict</option></select></label><label><span>Status</span><select value={status} onChange={e=>reset(()=>{setStatus(e.target.value);if(e.target.value!=="unresolved")setReason("all")})}><option value="paper">Analysis-ready (score 0–4)</option><option value="unresolved">Unresolved after V1.2 QC</option><option value="all">All observations</option></select></label>{status==="unresolved"&&<label><span>V1.2 unresolved reason</span><select value={reason} onChange={e=>reset(()=>setReason(e.target.value))}><option value="all">All remaining conflicts (113)</option>{qcOrder.map(k=><option key={k} value={k}>{qcLabels[k]} ({reasonCounts[k]||0})</option>)}</select></label>}</>:<label><span>Change type</span><select value={kind} onChange={e=>reset(()=>setKind(e.target.value))}><option value="all">All score changes</option><option value="0 → support">0 → support (135)</option><option value="support → 0">Support → 0 (146)</option><option value="risk increase">Risk increase (168)</option><option value="risk decrease">Risk decrease (181)</option><option value="low → material">0–2 → 3–4 (63)</option><option value="material → low">3–4 → 0–2 (47)</option></select></label>}</div>
   <div className="financing-result-line"><strong>{active.length.toLocaleString()}</strong> matching {mode==="brand"?"brand-year observations":"consecutive-year score changes"}<span>{mode==="brand"&&status==="unresolved"?(reason==="all"?"Production V1.2: 113 conflicts remain after chronology / identity QC. Select a reason to inspect a specific retained-conflict class.":`V1.2 reason: ${qcLabels[reason]||reason}. Click Compare versions to inspect source/state, date, score and Item 10 evidence.`):mode==="changes"?"Each row shows before/after evidence. Click Compare years to open the full extracted Item 10 text for both years.":"Click a row to inspect the original extracted text."}</span></div>
   {loading&&<div className="financing-loading">Loading V1.2 evidence dataset…</div>}{error&&<div className="financing-error">{error}</div>}
   {!loading&&!error&&mode==="brand"&&<div className="financing-table-wrap"><table className="financing-evidence-table"><thead><tr><th>Franchise system / offering</th><th>Year</th><th>Score / QC reason</th><th>Form / provider</th><th>{status==="unresolved"?"Conflicting sources":"Original evidence excerpt"}</th><th></th></tr></thead><tbody>{visibleBrand.map(r=><Fragment key={r.id}><tr><td><strong>{displayBrand(r.chainId,r.brand)}</strong><small>{r.chainId} · {r.documents} documents · {r.sources.join(" / ")||"source n/a"}</small></td><td>{r.year}</td><td><Badge score={r.score}/>{r.score===null?<small>{qcLabel(r)}</small>:<small>{r.status==="V1_2_CHRONOLOGY_RESOLVED"?"Chronology resolved":r.status}</small>}</td><td><strong>{joined(r.forms)}</strong><small>{joined(r.providers)}</small></td><td>{r.score===null?<><strong>Sources / state sources in conflict</strong><p>{r.sources.join(" / ")||"Not recorded"}</p><small>{r.qcReason}</small></>:<p>{r.evidenceQuote||"—"}</p>}</td><td><button onClick={()=>openRow(r)}>{selected?.id===r.id?"Close":r.score===null?"Compare versions":"View original"}</button></td></tr>{selected?.id===r.id&&<tr className="financing-inline-detail-row"><td colSpan={6}><InlineBrandDetail row={r} detail={detail} loading={detailLoading} onClose={()=>{setSelected(null);setDetail(null)}}/></td></tr>}</Fragment>)}</tbody></table></div>}
   {!loading&&!error&&mode==="changes"&&<div className="financing-table-wrap"><table className="financing-evidence-table"><thead><tr><th>Franchise system / offering</th><th>Years</th><th>Score change</th><th>Before → after forms</th><th>Evidence</th><th></th></tr></thead><tbody>{visibleChangeRows.map(r=><Fragment key={r.id}><tr><td><strong>{displayBrand(r.chainId,r.brand)}</strong><small>{r.chainId}</small></td><td>{r.fromYear} → {r.toYear}</td><td><strong>{r.fromScore} → {r.toScore}</strong><small>Δ {r.scoreChange>0?`+${r.scoreChange}`:r.scoreChange}</small></td><td><strong>{joined(r.fromForms)} → {joined(r.toForms)}</strong><small>{joined(r.fromProviders)} → {joined(r.toProviders)}</small></td><td><p>{r.fromQuote}</p><p>{r.toQuote}</p></td><td><button onClick={()=>openChange(r)}>{selectedChange?.id===r.id?"Close":"Compare years"}</button></td></tr>{selectedChange?.id===r.id&&<tr className="financing-inline-detail-row"><td colSpan={6}>{detailLoading?<div className="financing-loading">Loading both years…</div>:compare?<div className="financing-inline-versions compare"><div><h3>{r.fromYear} · Score {r.fromScore}</h3>{compare.before.versions.map((v,i)=><VersionCard key={`${v.hash}-${i}`} version={v} index={i}/>)}</div><div><h3>{r.toYear} · Score {r.toScore}</h3>{compare.after.versions.map((v,i)=><VersionCard key={`${v.hash}-${i}`} version={v} index={i}/>)}</div></div>:null}</td></tr>}</Fragment>)}</tbody></table></div>}
   {!loading&&!error&&<Pager page={p} pages={pages} setPage={n=>{setPage(n);setSelected(null);setDetail(null);setSelectedChange(null);setCompare(null)}}/>}
 </div>;
}
